### ISSUE TITLE
yAxis label are crowded

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#112]
It seems that when the distribution on the yAxis is too small the labels are crowded need a solution similar to xAxis where we could distinguish the labels. See attached screenshots!

![traffic_graph](https://user-images.githubusercontent.com/4873481/52229241-4f61d700-2869-11e9-9ad4-47555e89ef09.PNG)
![sla_graphs](https://user-images.githubusercontent.com/4873481/52229246-50930400-2869-11e9-80cf-eb7155dd0c3f.PNG)

@nxanil  Please treat this with hight priority as well and provide a fix by Wed

**Comment by nxanil** [comment]
@natabal 
Fixed in PR #115. Please have a look.
