### ISSUE TITLE
FlowVisualization:CSV downloaded shows 'timezones' as 'Last 24' and 'Prev 24' irrespective of the Time Interval selected

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#129]
Download CSV from '# Flows', '# Flows allowed by explicit ACL', '# Flows Denied by explicit ACL', '# Flows allowed by default ACL' and '# Flows denied by default ACL'.
Hat selected Time Interval of 15minutes. In 'timezones', it displays 'Last 24' and 'Prev 24'. Is should show 'Last 15min' and 'Prev 15min'.

Eg (From '# Flows'):
"value","timezones"

"2","Last 24"

"2","Prev 24"

However, it displays the values corresponding to 15min interval only.

**Comment by nxanil** [comment]
@natabal 

It seems like it is displaying key value of `aggs->timezones->filters->filters` property of elastic search query instead of time interval. For e.g - 

![Peek 2019-03-01 13-13](https://user-images.githubusercontent.com/26645756/54208561-2e447400-4502-11e9-87e0-8493d5419667.gif)


![Peek 2019-03-12 20-02](https://user-images.githubusercontent.com/26645756/54208395-da398f80-4501-11e9-866c-ce9dfcdc877b.gif)

**Comment by natabal** [comment]
@nxanil I am not familiar with this feature how do we fix this?

**Comment by nxanil** [comment]
@natabal 

We can fix it by making some changes in configuration files. 
For example, we can make `aggs` keys (`Prev 24` && `Last 24`) of elastic search dynamic. So when we make any changes in time interval drop-down, it replace `aggs` keys from selected drop-down value. For e.g - 
Here we need to replace `Prev 24` from `Prev {{duration:24}}{{unit:h}}` and 
`Last 24` from `Last {{duration:24}}{{unit:h}}` as seen in below screenshot:-


![vss-domain-flow-flow-metric](https://user-images.githubusercontent.com/26645756/54359499-c704fc00-4688-11e9-8d1a-b6ae90394da9.png)

![vss-domain-flow-flow-metric_viz](https://user-images.githubusercontent.com/26645756/54359500-c79d9280-4688-11e9-873a-6b6589dc0893.png)

and output of downloaded file is as:- 

![Screenshot from 2019-03-14 18-50-56](https://user-images.githubusercontent.com/26645756/54360115-23b4e680-468a-11e9-8347-7c99998f7bac.png)


Let me know your thought?

**Comment by natabal** [comment]
@nxanil I am fine with this but this approach!
