### ISSUE TITLE
Legend needs to be scrollable

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#146]
Text of the legend goes out of view and gets cut as they grow in numbers. See the attach view:

<img width="824" alt="Screen Shot 2019-04-15 at 5 17 48 PM" src="https://user-images.githubusercontent.com/4873481/56371831-b4fc0900-61b2-11e9-8932-bc7147c642a0.png">

**Comment by natabal** [comment]
@nxanil Please have a look at this ASAP. It must go in early next week. Thanks!

**Comment by nxanil** [comment]
@natabal 
This issue fixed.
