### ISSUE TITLE
Need distinct colors in graphs

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#151]
Tracks issue 1 in http://mvjira.mv.usa.alcatel.com:8080/browse/VRS-15315

Graphs "appear" to be using same colors.

In the pie graph example below, both VNC and TABOOLA appear to be using the same color. Similarly, colors used for GOOGLE and SSL look alike.
This is confusing to the user.

<img width="847" alt="Screen Shot 2019-04-30 at 11 17 18 AM" src="https://user-images.githubusercontent.com/24920919/56984093-18365580-6b3a-11e9-8058-4cfb67b78a63.png">

Similar issue can be noticed on the bar graph as well.

Visually distinct colors are to be used in such graphs.

**Comment by killanch** [comment]
@nxanil Can you pls have a look?

**Comment by nxanil** [comment]
@natabal 
This issue has been fixed.
