### ISSUE TITLE
Need mechanism to link colors across visualization

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#152]
Tracks issue 2 in http://mvjira.mv.usa.alcatel.com:8080/browse/VRS-15315

Need a mechanism for configuring same colors for same metric/key across visualizations.

For example, in the screenshots below, SSL uses blue in the bar chart, and green in pie chart.

<img width="842" alt="Screen Shot 2019-04-30 at 11 36 24 AM" src="https://user-images.githubusercontent.com/24920919/56985010-3c933180-6b3c-11e9-8807-1f2c42d6977e.png">
<img width="282" alt="Screen Shot 2019-04-30 at 11 35 57 AM" src="https://user-images.githubusercontent.com/24920919/56985012-3c933180-6b3c-11e9-9003-df2d7a7b66ad.png">

**Comment by killanch** [comment]
@nxanil Can you pls take a look?

**Comment by nxanil** [comment]
@natabal 
This issue has been fixed
