### ISSUE TITLE
Need mechanism to conditionally show/hide dashboard

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#154]
Need a mechanism to show or hide a specific dashboard based on a boolean flag passed as parameter

**Comment by killanch** [comment]
@natabal Can you pls assign this ticket

**Comment by natabal** [comment]
@nxanil Please provide a way to show/hide dashboards similarly to how we show/hide the `VSS/AAR Analytics` today!

**Comment by nxjiten** [comment]
@natabal 

We need to show/hide the dashboard menu button so that there will be no option to open the dashboard?
Please suggest us how to implement the same.
