### ISSUE TITLE
Table: Header row to remain fixed

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#167]
JIRA ticket: http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-24399

Sample:

Header row does not remain fixed when table is scrolled,
![tableb4](https://user-images.githubusercontent.com/24920919/59138979-0d46c000-8945-11e9-87c1-5b3792ee3d6b.gif)

With `fixedHeader` prop passed as true, data row columns are not aligned with header row columns.

We need fixed header row with all columns properly aligned.

**Comment by killanch** [comment]
@nxanil @natabal Pls re-assign as appropriate

**Comment by natabal** [comment]
@nxjiten Please take a look at this ticket.
