### ISSUE TITLE
ChordGraph - colorColumn not being used

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#168]
`colorColumn` configuration parameter is not being used by ChordGraph

In ChordGraph implementation, we have
```
ribbons
        .attr("d", ribbon)
        .style("fill", function(d) {
          return color(matrix.names[d.source.index]);
        })
        .style("stroke", "black")
....
```
Color seems to be always based on source.index.

In attached example, when 'To Underlay' is chosen, both ribbons appear in same color,

![subnetissue](https://user-images.githubusercontent.com/24920919/59274888-17e8aa00-8c10-11e9-9569-d724d22538ef.gif)

**Comment by killanch** [comment]
@natabal @nxanil Pls have a look

**Comment by killanch** [comment]
@nxanil could you pls check this?

**Comment by nxanil** [comment]
@killanch 

This issue is already fixed.

![chordGraph_issue](https://user-images.githubusercontent.com/26645756/102203407-905bb580-3eee-11eb-8a19-8791839e06f2.gif)
