### ISSUE TITLE
Table header row appears garbled - after fixed header row changes

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#174]
Table header row appears garbled - with recent fixed header row changes

@natabal @nxanil Pls re-assign as appropriate

Sample:
<img width="465" alt="Screen Shot 2019-06-13 at 5 08 23 PM" src="https://user-images.githubusercontent.com/24920919/59474989-f6e5ac00-8dfd-11e9-9537-57fbb6ca3889.png">

<img width="1106" alt="Screen Shot 2019-06-13 at 4 06 39 PM" src="https://user-images.githubusercontent.com/24920919/59473051-80dd4700-8df5-11e9-8423-276bcbb6d0bc.png">

**Comment by natabal** [comment]
@nxjiten Please treat this with high priority

**Comment by killanch** [comment]
fixed
