### ISSUE TITLE
Chord Graph - stops responding to filter change

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#193]
Steps to reproduce:
1. Open VSS flow graph - with default ACL Action `Allow`, the graph gets displayed - this is expected
2. Change ACL Action to `Deny`, no matching flows and hence no data to visualize - this is expected
3. After this, if action is changed back to `Allow`, graph displayed in step 1 is not displayed anymore. It requires re-selection of same action `Allow` again for the graph to get rendered
4. After this behavior becomes unpredictable, at some point the graph becomes empty. Even the `No data to visualize` text is not displayed.

Sample:
![chord2](https://user-images.githubusercontent.com/24920919/60363919-a5125980-9999-11e9-915a-b3dcfaab4c9d.gif)

**Comment by killanch** [comment]
@nxanil Can you pls take a look?
cc @natabal

**Comment by natabal** [comment]
@nxanil It seems that the graph does not get painted!
