### ISSUE TITLE
Chord Diagram doesn't show any error message when there is any connectivity issue

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#202]
When there is connectivity issue chord diagrams are not getting updated but also it is not showing any error/warning message.
Can we please have it checked.
As it is an intermittent issue I don't have screenshot now, but will attach it once I face it again.

**Comment by natabal** [comment]
@AnamikaDubey07 As per our conversation during Mon's meeting please add here the steps to reproduce this issue.

**Comment by nxjiten** [comment]
@AnamikaDubey07,

Please write down the steps to reproduce this issue.

**Comment by AnamikaDubey07** [comment]
In Flow Explorer After changing time interval Flows per domain Diagram is not visible.
PFA

**Comment by AnamikaDubey07** [comment]
![ScreenShot_NetworkError](https://user-images.githubusercontent.com/53247988/62121432-32bacf00-b2e1-11e9-8bd9-a91503cb1d1b.png)
[nuage_Flow.txt](https://github.com/nuagenetworks/vis-graphs/files/3446312/nuage_Flow.txt)
[Network_Error.txt](https://github.com/nuagenetworks/vis-graphs/files/3446315/Network_Error.txt)
[Console.txt](https://github.com/nuagenetworks/vis-graphs/files/3446317/Console.txt)

**Comment by nxjiten** [comment]
> In Flow Explorer After changing time interval Flows per domain Diagram is not visible.
> PFA

I will look into it.

**Comment by nxjiten** [comment]
@AnamikaDubey07 

Could you please provide the video for the same or steps to reproduce the same issue?
