### ISSUE TITLE
Line Graph showing discontinued lines

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#206]
I have a line graph that plots a series over time. The query will return the number of hits over a period of time. The data is collected every 10 min however at times the timestamp for each row inserted every 10 min could differ by a few mills. In these situations the lines show broken in the LineGraph.

<img width="1090" alt="Screen Shot 2019-07-30 at 4 29 31 PM" src="https://user-images.githubusercontent.com/4873481/62172854-a6aca580-b2e8-11e9-8c06-35b28fa1d75e.png">

[gw-selection.txt](https://github.com/nuagenetworks/vis-graphs/files/3449224/gw-selection.txt)

**Comment by natabal** [comment]
For the queries and visualization configuration please refer to this [PR](https://github.com/nuagenetworks/vis-config/pull/88)

**Comment by nxjiten** [comment]
Hi @natabal

There is a property `showNull` which is `false` in setting file (`nsg-gw-selection` ).

This property is used to show/hide null value points on line graph while drawing lines.

![02286d583715cb837e48c908705de6dc](https://user-images.githubusercontent.com/49763726/62210997-1723f700-b3bb-11e9-8822-18f4305e9f4b.png).

Please let me know if I am missing anything.

**Comment by natabal** [comment]
Thanks @nxjiten I think I missed the second showNull in my config.

**Comment by natabal** [comment]
<img width="1079" alt="Screen Shot 2019-07-31 at 12 18 42 PM" src="https://user-images.githubusercontent.com/4873481/62467517-d0325a80-b748-11e9-833d-3a6f8750a21a.png">
