### ISSUE TITLE
Table search option issue

### ISSUE THREAD

**Issue by shashank-nx** [nuagenetworks/vis-graphs#213]
@nxanil @nxjiten @natabal 

After clicking on search option in table graph, it show search option. This search option popup position is fixed, then scrolling in page its value is above our graph. Because of this unable to view and verify graph data.
![TableSearch](https://user-images.githubusercontent.com/47311742/63489908-03a71000-c4d1-11e9-84a1-2e37653b208e.gif)

**Comment by natabal** [comment]
@nxanil Can you please have a look?

**Comment by natabal** [comment]
@shashank-nx available in PR

**Comment by killanch** [comment]
@shashank-nx can you pls validate if fixed and close this issue?

**Comment by shashank-nx** [comment]
@killanch 

Working fine at my end.
