### ISSUE TITLE
Line Graph - x-axis time format to be accepted in config

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#217]
Today `xTickFormat` is used in `xAxis.tickFormat(format(xTickFormat))`.

But in a dateHistogram graph, the x-axis will be in time scale. And if xTickFormat is used to specify a time format (for example "%m/%d %H:%M"), it results in an error.

For time, we will have to use d3.timeFormat().

This needs to be implemented for LineGraph

**Comment by nxanil** [comment]
@killanch 
This issue has been fixed. Please verify this.

**Comment by killanch** [comment]
@nxanil verified, works as expected
