### ISSUE TITLE
Table - unselected default columns re-appear on changing any filter or on table refresh

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#220]
After unselecting a default column, it gets removed from the table.

But if any filter is changed, or if table refresh is invoked, the unselected default columns re-appear on table reload.

Sample:
In the example below, Timestamp, Source IP, Source Port, Destination IP and Destination Port were all unselected. But on changing the time interval filter, they re-appear on the same table.

![tableissue](https://user-images.githubusercontent.com/24920919/63975043-eb03a080-ca62-11e9-8b39-fd91a95ede60.gif)

This is not the case with non-default column. A non-default column which user selects, remains selected on table reload.

**Comment by killanch** [comment]
@natabal Pls have a look. You may close if you feel this behavior is OK. But it was annoying for me to keep unselecting the columns that I was not interested in.

**Comment by natabal** [comment]
@nxjiten please have a look. Thanks

**Comment by killanch** [comment]
fixed
