### ISSUE TITLE
Chord Diagram needs to pass listeners onClick on a ribbon

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#221]
When clicking on a ribbon on Chord diagram we load a table with the flow between a source and destination however we need more information to pass to for the query to correctly get the data. Presently only source and destination get passed to onMarkClick.

In addition, values of any other listener parameters specified in visualization configuration also need to be passed.

**Comment by nxanil** [comment]
@natabal I want to have a discussion on this, as we are calculating the cumulative data on this on the client-side, therefore, how we can get more information on this, unlike other charts.
This is a bit different from other charts.
