### ISSUE TITLE
Multiline Graph - Tooltip issues

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#234]
This is related to JIRA ticket: http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-33131

In a multiline graph, below 2 issues were observered.

**Issue 1**: As long as data is present, tooltips get rendered correctly.
But when we move to line without any data points, invalid timestamp tooltip gets displayed.
Sample below:
![multilinetooltip](https://user-images.githubusercontent.com/24920919/65362679-3a01a900-dbbd-11e9-8801-f826ad60acae.gif)

Tooltip configuration for the above,
```
"tooltip": [
    { "column": "cpu", "label": "CPU (%)", "format": "0.2f" },
    { "column": "memory", "label": "Memory (%)", "format": "0.2f" },
    { "column": "to", "label": "Timestamp", "timeFormat": "%b %d, %Y %X" }
]
```

**Issue 2**: Tooltip information goes missing after revisiting graph after a 'no-data' date.
In the example below, 
1. Initially tooltips get displayed correctly
2. Now select a date where there is no data (Issue 1 can be noticed now)
3. Now revisit date (as in Step 1). Now tool tips are visible only on the top half of the graph. When mouse is hovered over the bottom half, no tooltip is seen.
![multilinetooltip2](https://user-images.githubusercontent.com/24920919/65363350-2a379400-dbc0-11e9-825b-2c91e4a52c9f.gif)

**Comment by killanch** [comment]
@nxanil can you pls have a look?
cc @natabal

**Comment by natabal** [comment]
@nxanil the item 2 is not fixed

**Comment by killanch** [comment]
@nxanil I noticed this in latest build. When there is no data, we have a blank tooltip. Instead, can we avoid showing the tooltip?
![tt1](https://user-images.githubusercontent.com/24920919/66522558-8f392800-eaa2-11e9-96c8-7086ae8d565d.gif)

cc @natabal

**Comment by natabal** [comment]
@nxanil The issue #2 and the empty tooltip needs to be addressed as well. Thanks

**Comment by killanch** [comment]
fixed
