### ISSUE TITLE
Table style inconsistency

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#240]
If `selectColumnOption` is not specified, **bottom** of the table does not seem to align properly.
Sample:
<img width="1106" alt="WithoutSelect" src="https://user-images.githubusercontent.com/24920919/65920488-f9abe300-e393-11e9-897a-838bf1fffb05.png">

The same table appears to be fine with `selectColumnOption` set as `true`,
<img width="1109" alt="WithSelectCols" src="https://user-images.githubusercontent.com/24920919/65920496-ffa1c400-e393-11e9-972c-cb0a8ff0d2a6.png">

**Comment by killanch** [comment]
@nxanil can you pls take a look?
cc @natabal

**Comment by nxjiten** [comment]
@killanch, @natabal 
Please have a look. PR: #241

**Comment by natabal** [comment]
@killanch Please verify in master.

**Comment by killanch** [comment]
@natabal verified, looks good to me.
