### ISSUE TITLE
Style change needed for no data text

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#257]
When line graph is used for stats, with no data, the graph appears as below.
This uses `center-text` from `Graphs/style.css`

<img width="1095" alt="Screen Shot 2019-10-16 at 3 39 39 PM" src="https://user-images.githubusercontent.com/24920919/66964404-62998900-f02b-11e9-8b8f-7e474b780ebd.png">

Instead we need something like below,

<img width="1095" alt="Screen Shot 2019-10-16 at 3 38 34 PM" src="https://user-images.githubusercontent.com/24920919/66964405-63321f80-f02b-11e9-998c-a8658080104c.png">

**Comment by killanch** [comment]
@nxanil @natabal can you pls have a look?

**Comment by nxanil** [comment]
@killanch 
It would be great if you provide this graph for us because it is very tough to calculate dynamic width at runtime to centralize the text. If I will get this graph config then it will be easy for us to centralize the text.
Else another solution is to fix the width of the calendar (in percentage or pixel) into the graph and then calculate the width.

**Comment by killanch** [comment]
@nxanil The config used is as below,
```
data: {
            dateHistogram: true,
            xColumn: "to",
            yColumn: selectedMetrics.map(metric => metric.name),
            linesColumn: getLinesColumn(selectedMetrics, colorsArray),
            tooltip: getToolTipsObj(selectedMetrics),
            xTickFontSize: '1em',
            yTickFontSize: '1em',
            margin: {
                top: 10, bottom: 5, left: 5, right: 0
            }
        }
```
You may refer to https://github.com/nuagenetworks/vsd-react-ui/blob/master/src/EntityStats/MetricsGraph.js for details of the same.

We are rendering <RadioButtonAsAValue/> before <GraphView/>.
And we render <MetricsComponent/> after <GraphView/>.

**Comment by nxanil** [comment]
@natabal
Already merged, therefore closing this ticket
