### ISSUE TITLE
Table: On removing filter, unable to scroll to next page

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#258]
JIRA ticket: http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-38423

On removing filter, user is unable to scroll to next page. Only the first page is viewable.

Steps to reproduce:
1. Start with a table with large number of rows (210 in example below)
2. Choose a filter that will not match any rows - empty table displayed as expected
3. Clear the filter. Now table content in step 1 is expected to be displayed. Instead, only the first 20 rows (limit used is 20) is displayed. User is unable to view the remaining rows or scroll to subsequent pages.

Screen capture:
![tableissue](https://user-images.githubusercontent.com/24920919/67056892-ff7b2580-f102-11e9-8c1b-d4941a4bab2e.gif)

**Comment by killanch** [comment]
@nxjiten Can you pls have a look?
cc @natabal

**Comment by natabal** [comment]
@nxjiten We need a fix asap. Thanks!

**Comment by natabal** [comment]
@nxanil Please provide a fix for this

**Comment by natabal** [comment]
@killanch Is this fixed?

**Comment by killanch** [comment]
@natabal yes, we already brought in and merged the fix https://github.com/nuagenetworks/vsd-react-ui/pull/3337
I had assigned the corresponding JIRA ticket to Neeharika for validation
