### ISSUE TITLE
Pie Graph - legend text truncated

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#260]
- Complete text is not displayed in legend
- Also noticed that the top edge of the text is getting cut

Sample:
<img width="563" alt="Screen Shot 2019-10-18 at 10 58 02 AM" src="https://user-images.githubusercontent.com/24920919/67116989-6c8bcb00-f196-11e9-8dbf-e7ee9f5f7500.png">

**Comment by killanch** [comment]
@natabal pls re-assign as appropriate

**Comment by natabal** [comment]
@killanch Please adjust in the config.
