### ISSUE TITLE
Advanced search - eliminate needless _mapping elastic requests

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#261]
With `isAdvancedSearch` true configuration, every filter value change triggers an `_mapping` REST request to elasticsearch.
It appears that before every new elastic search, we are also triggering this `_mapping` request.
This is excessive, we could limit this request to just one, at the time of initial loading of the visualization.

Sample:
![mapping](https://user-images.githubusercontent.com/24920919/67133340-2730c300-f1c1-11e9-8bb4-10e942427ba6.gif)

**Comment by killanch** [comment]
@nxanil can you pls have a look?
cc @natabal

**Comment by nxanil** [comment]
@natabal 
Already merged, therefore closing this ticket
