### ISSUE TITLE
Table: Unable to select columns when row(s) selected

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#265]
When one or more rows is selected, I am unable to select columns.

Sample:

![tablecolumn](https://user-images.githubusercontent.com/24920919/67311384-4e82db00-f4b4-11e9-8043-62d50b61bd49.gif)

**Comment by killanch** [comment]
@nxjiten can you pls take a look?

**Comment by nxjiten** [comment]
@killanch 
It is a library feature where when we select any row(s) then it will hide select column options.
If you still need this feature (show select column) then we can look into it.

**Comment by killanch** [comment]
@natabal Could you pls confirm if we need this

**Comment by natabal** [comment]
@nxjiten I don't see a reason not to allow selection of new columns when the table has selected rows. Let's have this addressed after the current task is complete.

**Comment by natabal** [comment]
@killanch With the latest changes is this addressed?

**Comment by killanch** [comment]
@natabal yes, now able to select columns with row remaining selected,

![Screen Shot 2019-12-05 at 3 35 33 PM](https://user-images.githubusercontent.com/24920919/70283121-f60e5100-1774-11ea-9649-cba9805cb71b.png)
