### ISSUE TITLE
Table - height marginally more than specified configuration

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#294]
When the table has no data, its height is as per configuration, as below,

![Screen Shot 2019-11-20 at 2 49 25 PM](https://user-images.githubusercontent.com/24920919/69285194-2961b500-0ba5-11ea-9a6b-f7a4a2de477d.png)

But once data is populated, height grows,
![Screen Shot 2019-11-20 at 2 49 38 PM](https://user-images.githubusercontent.com/24920919/69285227-37afd100-0ba5-11ea-98c4-d380c1b1b910.png)

![th1](https://user-images.githubusercontent.com/24920919/69285234-3aaac180-0ba5-11ea-9183-375ff71e564d.png)

Table height is to remain constant, with or without data

**Comment by killanch** [comment]
@natabal @nxanil can you pls have a look?

**Comment by natabal** [comment]
@killanch Have all the items in this ticket been addressed?

**Comment by killanch** [comment]
@natabal yes, addressed
