### ISSUE TITLE
Line graph - does not get updated when props.configuration changes

### ISSUE THREAD

**Issue by killanch** [nuagenetworks/vis-graphs#316]
With `data` remaining same, if graph `configuration` alone gets changed, the line graph does not get re-rendered.

I see two issues, 
1. `shouldComponentUpdate` returns false
2. `componentDidUpdate` does not invoke `setConfiguredProperties()`

Expected behavior: New configuration is to be used and the graph should get re-rendered using the updated properties

This may be related to https://github.com/nuagenetworks/vis-graphs/commit/94b41887ce37a12c2d03fe6e6007a15d60ec9ef1#diff-1116100d89b596e3bcd5f044ce93df86

**Comment by killanch** [comment]
@nxanil can you pls have a look?
cc @natabal

**Comment by natabal** [comment]
@nxanil Please address this issue as well.

**Comment by killanch** [comment]
Fixed in https://github.com/nuagenetworks/vis-graphs/pull/341
