### ISSUE TITLE
Implement the Graphs on the basis of Pie Graph using Re-Charts and New Framework

### ISSUE THREAD

**Issue by nxanil** [nuagenetworks/vis-graphs#317]
Implement the new framework for the following charts:
- [x] Pie Graph - Anil
- [x] Text Graph - Anil
- [x] Area - Jiten
- [x] Line - Jiten
- [x] Variation Text Graph - Anil
- [x] Bar - Anil
- [x] Chord - Anil
- [x] Google Maps- Anil
- [x]  Port Graph - Anil
- [x] Heatmap - Jiten
- [x] Progress Bar Graph - Anil
- [x] Gauge Graph - Jiten
- [x] Table Graph - Jiten
- [x] Tree Graph - Anil

**Comment by nxanil** [comment]
`BarGraph`
 
`Simple BarGraph`

[![Screenshot from Gyazo](https://gyazo.com/193ccc46d7bb051fc5d206f169d6b12e/raw)](https://gyazo.com/193ccc46d7bb051fc5d206f169d6b12e)

`Stacked BarGraph`

[![Screenshot from Gyazo](https://gyazo.com/6195043f1e314bdaf00dccb144044de5/raw)](https://gyazo.com/6195043f1e314bdaf00dccb144044de5)

`Pie Graph`

`Standard PieGraph`

[![Screenshot from Gyazo](https://gyazo.com/35287ee8450343f614d979c3b46cdf2e/raw)](https://gyazo.com/35287ee8450343f614d979c3b46cdf2e)

`Percentage PieGraph`


[![Screenshot from Gyazo](https://gyazo.com/0387ff26dda2c889ea1ea386b36d5b49/raw)](https://gyazo.com/0387ff26dda2c889ea1ea386b36d5b49)

`SimpleText Graph`

[![Screenshot from Gyazo](https://gyazo.com/4979755b60b623cfcdc6ce32dc0cbd81/raw)](https://gyazo.com/4979755b60b623cfcdc6ce32dc0cbd81)


`VariationText Graph`

[![Screenshot from Gyazo](https://gyazo.com/f4e679a1662106d04679af60a3916ff2/raw)](https://gyazo.com/f4e679a1662106d04679af60a3916ff2)


`Port Graph`

[![Screenshot from Gyazo](https://gyazo.com/8a64aeb0c6b5c3bc4f2a3c882bc6f022/raw)](https://gyazo.com/8a64aeb0c6b5c3bc4f2a3c882bc6f022)

`Progress Bar Graph`

[![Screenshot from Gyazo](https://gyazo.com/e139a84900cb223285f05bafc81af17c/raw)](https://gyazo.com/e139a84900cb223285f05bafc81af17c)

**Comment by nxanil** [comment]
`Pie Graph`

`Simple Pie Graph`

[![Screenshot from Gyazo](https://gyazo.com/fae87bfebe00e3e14f6dcf397850747e/raw)](https://gyazo.com/fae87bfebe00e3e14f6dcf397850747e)

`Percentage Pie Graph`

[![Screenshot from Gyazo](https://gyazo.com/a1f7966c960350b4039bcc4dd121870f/raw)](https://gyazo.com/a1f7966c960350b4039bcc4dd121870f)

`Bar Graph`

`Custom Color BarGraph`

[![Screenshot from Gyazo](https://gyazo.com/6e21170973f13a8bbcc9ee25f41e1296/raw)](https://gyazo.com/6e21170973f13a8bbcc9ee25f41e1296)

`Stacked BarGraph`

[![Screenshot from Gyazo](https://gyazo.com/e45ebdc2f0a26f88bbc3dafe20cd3fa7/raw)](https://gyazo.com/e45ebdc2f0a26f88bbc3dafe20cd3fa7)

`Brushed BarGraph`

[![Screenshot from Gyazo](https://gyazo.com/a2ce32224bfa246e49da0eeb5c187148/raw)](https://gyazo.com/a2ce32224bfa246e49da0eeb5c187148)

**Comment by nxjiten** [comment]
`Line Graph`

![Line-graph](https://user-images.githubusercontent.com/49763726/74706864-13b06a00-523e-11ea-9c8a-8df992fd8d81.jpg)

`Gauge Graph`

![gauge-graph](https://user-images.githubusercontent.com/49763726/74706865-14e19700-523e-11ea-8b2c-8ed52f346074.jpg)

`Area Graph`

![Area-graph](https://user-images.githubusercontent.com/49763726/74706866-157a2d80-523e-11ea-8490-ff2f1d7f9281.jpg)

**Comment by nxjiten** [comment]
`HeatMap Graph`

![heatmapgraph](https://user-images.githubusercontent.com/49763726/75135774-a3578c00-5708-11ea-96e7-61ad71ee7607.jpg)

**Comment by nxanil** [comment]
`Chord Graph`

[![Screenshot from Gyazo](https://gyazo.com/c8b585f78182b35a247491550d0343b4/raw)](https://gyazo.com/c8b585f78182b35a247491550d0343b4)

**Comment by nxjiten** [comment]
`Table Graph`

![table-graph](https://user-images.githubusercontent.com/49763726/75850762-fff42e80-5e0d-11ea-889c-eb793e96b8a4.jpg)

**Comment by nxjiten** [comment]
`Gauge Graph`

![gaugegraph](https://user-images.githubusercontent.com/49763726/75883857-b9bcc080-5e49-11ea-8df2-7465d721ab55.jpg)
