### ISSUE TITLE
Table Search bar does not get re-rendered when there is results

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#358]
When search results return no data the error card replaces the whole card and the user cannot clear the search results. See the attached gif.

Please provide fixes for r6.0 and master.

![event_analytics3](https://user-images.githubusercontent.com/4873481/80617733-512c3300-89f7-11ea-8881-e842dffae483.gif)

**Comment by nxanil** [comment]
@natabal 

I have Fixed the above issue in master and have checked the same into r6.0. The above issue does not exist in r6.0.
