### ISSUE TITLE
ACL flow details chart - When user clicks on 'select columns' button, names are displayed behind the editor

### ISSUE THREAD

**Issue by sreddy80** [nuagenetworks/vis-graphs#370]
@natabal 
When user clicks on 'select columns' button, names are displayed behind the flows
![acl_select](https://user-images.githubusercontent.com/35505013/83789791-1186e580-a64c-11ea-96df-b855e2efbb59.gif)
 editor.

**Comment by natabal** [comment]
@sreddy80 Please verify this with latest and close if bug is fixed.

**Comment by sreddy80** [comment]
Verified
