### ISSUE TITLE
AreaGraph Issues

### ISSUE THREAD

**Issue by chaitanyahalbe** [nuagenetworks/vis-graphs#388]
Currently coming across a couple of issues in AreaGraph as shown in the screenshot:
![image](https://user-images.githubusercontent.com/46327518/90189053-5ed0b300-dd71-11ea-985c-f521c10f95da.png)

1. Tooltip:
- In my query the tooltip is something like below. But in the visualization, the tooltip is coming up data points as `value1 : value2`. The tooltip should have the label and format as mentioned in the query.
```
"tooltip": [
            { "column": "NetworkLoss", "label": "Avg % Network Loss", "format": "0.2f"},
            { "column": "LossAfterFEC", "label": "Avg % Loss after FEC", "format": "0.2f"},
            { "column": "ts", "label": "Timestamp", "timeFormat": "%b %d, %y %X"}
        ]
```

2. Legend:
- I am using 2 ES records for comparison in the AreaGraph. But there is no way to indicate the color mappings to the ES records in the legend. For example: `<Color blue circle>: Network Loss` and `<Color orange circle>: Loss after FEC`.

**Comment by chaitanyahalbe** [comment]
@natabal Open an issue for AreaGraph.

**Comment by natabal** [comment]
@nxanil Please treat this with the highest priority

**Comment by natabal** [comment]
@chaitanyahalbe If this is fixed please close.
