### ISSUE TITLE
Heatmap: when clicking on the heatmap exception in ReactTooltip

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#403]
```
index.es.js:1677 Uncaught TypeError: Cannot read property 'clientX' of null
    at getCurrentOffset (index.es.js:1677)
    at getPosition (index.es.js:1536)
    at ReactTooltip.updatePosition (index.es.js:2394)
    at index.es.js:2213
```
<img width="1067" alt="Screen Shot 2020-08-31 at 4 16 33 PM" src="https://user-images.githubusercontent.com/4873481/91777677-62ec3580-eba5-11ea-85f3-640b0d79e03b.png">

**Comment by killanch** [comment]
@chaitanyahalbe can you pls validate if this issue has been fixed?

**Comment by chaitanyahalbe** [comment]
> @chaitanyahalbe can you pls validate if this issue has been fixed?

@killanch This has already been verified. Closing this.
