### ISSUE TITLE
NAT-T visualization table-  Missing scroll bar

### ISSUE THREAD

**Issue by sreddy80** [nuagenetworks/vis-graphs#409]
- [x] Horizontal scroll bar is missing on NAT-T tables, as a result all column names are not visible. Only when open in a separate window, it works.

![image](https://user-images.githubusercontent.com/35505013/96163089-47778880-0ece-11eb-9ec1-3427b834649b.png)

**Comment by killanch** [comment]
@nxanil  Any update on this?
@sreddy80 tested and states that the issue is still not resolved

**Comment by sreddy80** [comment]
@nxanil - See the fix. Thanks!
