### ISSUE TITLE
Reduce whitespace in AreaGraphs and Heatmaps

### ISSUE THREAD

**Issue by chaitanyahalbe** [nuagenetworks/vis-graphs#416]
@nxanil There is a request from @jeroennokia and @AnamikaDubey07 to reduce the whitespace in the area graphs and heatmaps so that the data being displayed has more screen space. Can you please take a look and resolve this ASAP?
- Area Graph 
![image](https://user-images.githubusercontent.com/46327518/99741212-6fd24400-2a85-11eb-80b0-6f0ec59df583.png)

- Heatmap
![image](https://user-images.githubusercontent.com/46327518/99848817-51288780-2b2f-11eb-8c2f-f079f028b58b.png)

cc @killanch

**Comment by jeroennokia** [comment]
also regarding the bottom white space. The X-axis title "Time" seems to take up a lot of space. While in general i agree, that labeling axises is preferred (though 90% of our graphs i guess it would be time), i'm not sure if it justifies this much real estate.
