### ISSUE TITLE
MultiLineGraph Tooltip Issue

### ISSUE THREAD

**Issue by shashank-nx** [nuagenetworks/vis-graphs#418]
@killanch 

MultiLineGraph Tooltip does not showing correct tooltip value. Shows same value of for every tooltip label.

![Tooltip](https://user-images.githubusercontent.com/47311742/100748585-7f4c7800-3409-11eb-8050-2ae392cc9afb.png)

**Comment by killanch** [comment]
@shashank-nx could you pls fix this issue? 
The visualization config used in the above screenshot is, https://github.com/nuagenetworks/vis-config/blob/master/visualizations/nsg-gw-selection.json

**Comment by killanch** [comment]
@nxanil could you pls fix this issue? 
The visualization config used in the above screenshot is, https://github.com/nuagenetworks/vis-config/blob/master/visualizations/nsg-gw-selection.json

**Comment by chaitanyahalbe** [comment]
@shashank-nx What setup did you use to reproduce this issue?

**Comment by shashank-nx** [comment]
@chaitanyahalbe 

I am using this Setup: https://5fcbde9543198e9e406fbbce.labs.nuagex.io:8443/

**Comment by killanch** [comment]
@shashank-nx could you pls validate the fix?

**Comment by shashank-nx** [comment]
@killanch

it's working fine.

![workinfine](https://user-images.githubusercontent.com/47311742/102061802-e90d4e80-3e19-11eb-88fa-8c807af9434d.png)
