### ISSUE TITLE
BarGraph Tooltip Issue

### ISSUE THREAD

**Issue by preshitg** [nuagenetworks/vis-graphs#423]
Bar Graph tooltip does not display the correct value for the y column. Data being passed to the BarGraph component is correct, yet it does not pick the correct value to be displayed for the y column. It is picking up the x column value.

e.g. in the screenshot below, Domain value in the tooltip should have been 'vss-domain' instead of '50'
This is using `vss-top-domains-blocked-traffic.json`

![VssUI_Dashboard](https://user-images.githubusercontent.com/46327440/101675138-47978e80-3a0e-11eb-917b-5e6789f35bb8.png)

**Comment by killanch** [comment]
@nxanil could you pls fix this?

**Comment by nxanil** [comment]
This issue has been fixed.
