### ISSUE TITLE
Visualization Filter Issue

### ISSUE THREAD

**Issue by chaitanyahalbe** [nuagenetworks/vis-graphs#427]
@nxanil I am seeing this issue again. When I change the filter in one of the area graphs in visualizations, it also changes the filters in other visualizations on the same dashboard. Attached GIF.
![Viz_Filter_Issue](https://user-images.githubusercontent.com/46327518/102141844-54552180-3e16-11eb-9295-31a043c1afca.gif)

cc @killanch

**Comment by killanch** [comment]
@nxanil could you pls prioritize this as it breaks existing functionality?

**Comment by preshitg** [comment]
@nxanil : Can you please revisit this? This seems to have broken the vss domain flow graph for PG.
Details in this PR: https://github.com/nuagenetworks/vsd-react-ui/pull/4847

**Comment by nxanil** [comment]
@preshitg @chaitanyahalbe 
This issue had been resolved. We can close this issue.

**Comment by preshitg** [comment]
Closing this as fixed
