### ISSUE TITLE
FEC Explorer : For All numeric columns <=, >=, <, > search is not available

### ISSUE THREAD

**Issue by chaitanyahalbe** [nuagenetworks/vis-graphs#446]
This is applicable to all graphs of type `Table` and specifically to FEC Explorer. We need to add support for `<=, >=, <, >` operations in the search. Right now,   support is only available for `equals` and `not equals`.

cc @killanch 
Jira: http://mvjira.mv.usa.alcatel.com:8080/browse/VSD-51763

**Comment by chaitanyahalbe** [comment]
Hi @AnamikaDubey07 you can also use this issue to follow-up with @nxanil.

**Comment by AnamikaDubey07** [comment]
HI @nxanil  Can you please let me know if this is done.
Thanks

**Comment by nxanil** [comment]
@chaitanyahalbe @killanch @AnamikaDubey07 

This feature is only required for `FEC Explorer`. OR it is required for everywhere where `SearchBar` is present.

**Comment by chaitanyahalbe** [comment]
> @chaitanyahalbe @killanch @AnamikaDubey07
> 
> This feature is only required for `FEC Explorer`. OR it is required for everywhere where `SearchBar` is present.

@nxanil Currently, it is only required for FEC Explorer. But it will be good if we are able to enable or disable this feature through the config files just like we do for the searchBar right now.

**Comment by AnamikaDubey07** [comment]
@nxanil It will be good if we have this feature in VSS as well on flow explorer,event analytics tabs as well.
as suggested by chaitanya enable/disable through config file will be a good appoarch as per my understanding.

**Comment by nxanil** [comment]
@chaitanyahalbe @AnamikaDubey07 

Thanks for the quick reply. I will do the same. I will try to complete this by Friday EOD.

**Comment by killanch** [comment]
@chaitanyahalbe framework changes merged to 0.0 and r20.10. can you pls implement vis-config changes to enable numeric search on applicable tables?
