### ISSUE TITLE
Titles in graph component length need to have ellipsis

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#72]
Some titles are long and occupy the space of info and share buttons making it impossible to click on those buttons

For '# Flows allowed by explicit ACL', '# Flows Denied by explicit ACL', '# Flows allowed by default ACL' and '# Flows denied by default ACL', the mentioned title appear over info  and share buttons.

**Comment by nxanil** [comment]
Fixed in feature/viz-graphs branch
