### ISSUE TITLE
on changing the time interval, some UI elements are not changing accordingly

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#73]
On the enterprise dashboard, had earlier selected 15min Interval. Following field had the mentioned values:'#ACL Deny' was 7. '#Security Events' was 7.Changed Time interval to 24Hr. Now as per data present in elastic search, I expect following counts:'#ACL Deny' should be 10. '#Security Events' should be 10. But these fileds didnt change. However graphs changed correctly.This is reproducible 50% of the time. Keep changing interval between 15min and 24Hr. You will see this issue approx 50% of times.Note: When 15min interval is selected, '#Packets (24h)' shows counts corresponding to 15min. Its hould show last 24hr data only (because it has '24h' mentioned in its name). Even this filed is victim of this issue (Altough we dont expect it to change).
--

**Comment by nxanil** [comment]
@natabal 
I guess it is fixed.
