### ISSUE TITLE
Pie Graph size issues

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#77]
Pie Graph with lots of data is too small to be usable. And the labels on the pie graphs are making the graph unusable.

We need to:
- Labels on the graph should be hidden if the graph has more then 4 slices
- Legend needs to be fixed in size and provide a scroll

![screen shot 2018-12-06 at 2 23 07 pm](https://user-images.githubusercontent.com/4873481/49615473-8481a400-f962-11e8-9728-a45e5e24acc4.png)

**Comment by nxanil** [comment]
@natabal 
Fixed in PR - https://github.com/nuagenetworks/vsd-react-ui/pull/2005 for pie graph.
Need to fix the same case in other graphs as well.
